version: '3.4'

services:
  cadess:
    container_name: cadess
    image: cadess:0.1
    ports:
    - "443:8080"
    volumes:
    - '/opt/cades/cades.yaml:/cades/cades.yaml'
    - '/opt/cades/cades.db:/cades/cades.db'
    working_dir: /cades
    environment:
      CADES_PORT: 8080
    entrypoint:
    - python
    - apisrv.py
